version : '3.9'
services:
  dev-db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - my-network
  test-db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - 5435:5432
    networks:
      - my-network
networks:
  my-network: